services:
  db:
    container_name: weather-map-db
    image: postgres:latest
    restart: always
    shm_size: 128mb
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432

volumes:
  db_data:
