services:
  db:
    container_name: weatherdb
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  next-client:
    build:
      context: ./client
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development

  python-server:
    container_name: python-server
    build:
      context: ./server
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
volumes:
  db_data:
