services:
  db:
    container_name: weatherdb
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  next-client:
    container_name: next-client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_PYTHON_API=http://python-server:8000
      - NEXT_PUBLIC_CLIENT_API=http://localhost:8000
    command: ["pnpm", "run", "dev", "-p", "3000"]

  python-server:
    container_name: python-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/usr/src/app
      - ./server/wait-for-it.sh:/usr/src/app/wait-for-it.sh
    ports:
      - "8000:8000"
    environment:
      DB_NAME: weatherdb
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: pass
    depends_on:
      - db

volumes:
  db_data:
