services:
  db:
    container_name: weather-map-db
    image: postgis/postgis
    restart: always
    shm_size: 128mb
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432

volumes:
  db_data:
