services:
  db:
    container_name: weatherdb
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  next-client:
    container_name: client-dev
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_PYTHON_API=http://python-server:8000
      - NEXT_PUBLIC_CLIENT_API=http://localhost:8000

  python-server:
    container_name: python-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: weatherdb
      DB_HOST: weatherdb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: pass
    depends_on:
      - db

volumes:
  db_data:
