services:
  db:
    container_name: weatherdb
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  next-client:
    container_name: client-dev
    build:
      context: ./client
    image: nextjs-dev
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src
          ignore:
            - ./client/node_modules/
        - action: rebuild
          path: ./client/package.json
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

  python-server:
    container_name: python-server
    build:
      context: ./server
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app
    depends_on:
      - db
volumes:
  db_data:
