apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: metropolia-weather-map
  labels:
    app: fastapi-server
data:
  DB_NAME: weatherdb
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_USER: postgres
  MPLCONFIGDIR: /tmp/matplotlib