services:
  app:
    container_name: server-test-wsl
    build:
      context: .
      dockerfile: ./Dockerfile
    image: python-dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    environment:
      DB_NAME: weatherdb
      DB_HOST: weatherdb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: pass
