name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  release-please:
    uses: ForumViriumHelsinki/.github/.github/workflows/reusable-release-please.yml@main
    with:
      app-id: ${{ vars.CI_APP_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.CI_APP_PRIVATE_KEY }}
